version: '3.9'

services:
  pg:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet_service_db

  wallet-service:
    build: .
    ports:
      - 8001:8001
    depends_on:
      - pg
    environment:
      DB_PW: postgres
      DB_USER: postgres
      DB_URL: jdbc:postgresql://pg:5432/wallet_service_db
